package:
  name: orjson
  version: 3.10.15
  top-level:
    - orjson
source:
  url: https://files.pythonhosted.org/packages/source/o/orjson/orjson-3.10.15.tar.gz
  sha256: 05ca7fe452a2e9d8d9d706a2984c95b9c2ebc5db417ce0b7a49b91d50642a23e
requirements:
  executable:
    - rustup
build:
  script: export RUSTFLAGS="-Z link-native-libraries=yes"
about:
  home: https://github.com/ijl/orjson
  PyPI: https://pypi.org/project/orjson
  summary:
    Fast, correct Python JSON library supporting dataclasses, datetimes, and
    numpy
  license: Apache-2.0 OR MIT
